# name: GitHub Actions Demo
# on: [push]
# jobs:
#   Explore-GitHub-Actions:
#     runs-on: ubuntu-latest
#     steps:
#       - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
#       - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
#       - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
#       - name: Check out repository code
#         uses: actions/checkout@v3
#       - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
#       - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
#       - name: List files in the repository
#         run: |
#           ls ${{ github.workspace }}
#       - run: echo "ğŸ This job's status is ${{ job.status }}."

# name: GitHub Actions Demo # ì‘ì—…íƒ­ì— í‘œì‹œë  ì›Œí¬í”Œë¡œ ì´ë¦„
# on: [push] # trigger
# jobs: # ì›Œí¬í”Œë¡œ ì—ì„œ ì‹¤í–‰ë˜ëŠ” ëª¨ë“  ì‘ì—…ì˜ ê·¸ë£¹í™”í•©ë‹ˆë‹¤ .
#   check-bats-version:
#     runs-on: ubuntu-latest # ì–´ë””ì„œ ì‹¤í–‰ë  ì§€ - ìš°ë¶„íˆ¬ ìµœì‹ ì—ì„œ ì‘ì—…í•œë‹¤ ëª…ì‹œ
#     steps: # ì‘ì—…ì— ì‹¤í–‰ë  ë‹¨ê³„ ëŒ€í•œ ê·¸ë£¹í™”
#       - uses: actions/checkout@v3 # 
#       - uses: actions/setup-node@v3 # ì§€ì •ëœ ë…¸ë“œë¥¼ ì‚¬ìš©í•¨.
#         with:
#           node-version: '14'
#       - run: npm install -g bats
#       - run: bats -v

name: node test
on: [push]
jobs:
  greeting_job:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        uses: jonnung/github-action-practice@master
        with:
          who-to-greet: 'Jonnung'
        id: hello
      - name: Echo the greeting's time
        run: echo 'The time was ${{ steps.hello.outputs.time }}.'
      - name: Get vercel token
        run: echo '${{ secrets.VERCEL_TOKEN }}'